# Generated by Django 5.2.6 on 2025-09-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('gmail', 'Gmail'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], default='whatsapp', max_length=50),
        ),
    ]
