# Generated by Django 5.2.6 on 2025-09-13 23:25

import django.core.validators
import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('master', models.CharField(choices=[('buddha', 'Buddha'), ('osho', 'Osho'), ('krishna', 'Krishna')], max_length=20)),
                ('content_type', models.CharField(choices=[('teaching', 'Teaching'), ('book', 'Book'), ('video', 'Video'), ('blog', 'Blog')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('excerpt', django_summernote.fields.SummernoteTextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'unique_together': {('master', 'content_type', 'slug')},
            },
        ),
    ]
