# Generated by Django 5.2.6 on 2025-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='amazon_buy_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='flipkart_buy_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
