# Generated by Django 5.2.6 on 2025-09-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
