# Generated by Django 5.2.6 on 2026-01-17 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
